---
- name: Push Code
  hosts: nest
  tasks:
    - name: Copy Executable
      ansible.builtin.copy:
        src: sysmonitor
        dest: /tmp/
    - name: Move Executable
      command: install --owner=root --group=root /tmp/sysmonitor /usr/local/bin/
      become: true